{
  "_from": "fastify-error@^0.2.0",
  "_id": "fastify-error@0.2.0",
  "_inBundle": false,
  "_integrity": "sha512-zabxsBatj59ROG0fhP36zNdc5Q1/eYeH9oSF9uvfrurZf8/JKfrJbMcIGrLpLWcf89rS6L91RHWm20A/X85hcA==",
  "_location": "/fastify-error",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "fastify-error@^0.2.0",
    "name": "fastify-error",
    "escapedName": "fastify-error",
    "rawSpec": "^0.2.0",
    "saveSpec": null,
    "fetchSpec": "^0.2.0"
  },
  "_requiredBy": [
    "/fastify"
  ],
  "_resolved": "https://registry.npmjs.org/fastify-error/-/fastify-error-0.2.0.tgz",
  "_shasum": "9a1c28d4f42b6259e7a549671c8e5e2d85660634",
  "_spec": "fastify-error@^0.2.0",
  "_where": "/home/vijayakumar_psg587/Documents/Code/Nestjs/fastify-auth-sample/node_modules/fastify",
  "author": {
    "name": "Tomas Della Vedova"
  },
  "bugs": {
    "url": "https://github.com/fastify/fastify-error/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "A small utility, used by Fastify itself, for generating consistent error objects across your codebase and plugins.",
  "devDependencies": {
    "ava": "^3.9.0",
    "standard": "^14.3.4",
    "tsd": "^0.11.0"
  },
  "homepage": "https://github.com/fastify/fastify-error#readme",
  "keywords": [
    "fastify",
    "error",
    "utility",
    "plugin"
  ],
  "license": "MIT",
  "main": "index.js",
  "name": "fastify-error",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/fastify/fastify-error.git"
  },
  "scripts": {
    "test": "standard && ava -v && tsd"
  },
  "types": "index.d.ts",
  "version": "0.2.0"
}
